<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.2.RELEASE</version>
    </parent>
    <groupId>com.bw.saml</groupId>
    <artifactId>saml</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>saml</name>
    <description>saml系统</description>

  <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
      <java.version>1.8</java.version>
      <log4j2.version>2.17.0</log4j2.version>
  </properties>

  <dependencies>
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
          <exclusions>
              <exclusion>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-logging</artifactId>
              </exclusion>
          </exclusions>
      </dependency>
      <dependency> <!-- 引入log4j2依赖 -->
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-log4j2</artifactId>
      </dependency>
      <!-- 加上这个才能辨认到log4j2.yml文件 -->
      <dependency>
          <groupId>com.fasterxml.jackson.dataformat</groupId>
          <artifactId>jackson-dataformat-yaml</artifactId>
      </dependency>
      <!--用于日志存储，不引用打包时会找不到JDBCAppender -->
      <dependency>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
          <version>1.2.17</version>
      </dependency>
      <dependency>
          <groupId>commons-codec</groupId>
          <artifactId>commons-codec</artifactId>
          <version>1.10</version>
      </dependency>
      <dependency>
          <groupId>commons-lang</groupId>
          <artifactId>commons-lang</artifactId>
          <version>2.1</version>
      </dependency>
      <dependency>
          <groupId>commons-collections</groupId>
          <artifactId>commons-collections</artifactId>
          <version>3.1</version>
      </dependency>

      <dependency>
          <groupId>opensaml</groupId>
          <artifactId>opensaml</artifactId>
          <version>2.2.3</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/opensaml-2.2.3.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>joda-time</groupId>
          <artifactId>joda-time</artifactId>
          <version>1.5.2</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/joda-time-1.5.2.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>xmltooling</groupId>
          <artifactId>xmltooling</artifactId>
          <version>1.2.0</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/xmltooling-1.2.0.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>openws</groupId>
          <artifactId>openws</artifactId>
          <version>1.2.2</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/openws-1.2.2.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>serializer</groupId>
          <artifactId>serializer</artifactId>
          <version>1.5</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/serializer-2.9.1.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>xerces</groupId>
          <artifactId>xerces</artifactId>
          <version>1.5</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/xercesImpl-2.9.1.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>xmlsec</groupId>
          <artifactId>xmlsec</artifactId>
          <version>1.4.2</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/xmlsec-1.4.2.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>velocity</groupId>
          <artifactId>velocity</artifactId>
          <version>1.5</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/velocity-1.5.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>bcprov-ext</groupId>
          <artifactId>bcprov-ext</artifactId>
          <version>1.40</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/lib/bcprov-ext-jdk15-1.40.jar</systemPath>
      </dependency>
      <dependency>
          <groupId>dom4j</groupId>
          <artifactId>dom4j</artifactId>
      </dependency>
  </dependencies>
    <build>
<!--        <resources>-->
<!--            <resource>-->
<!--                <directory>src/main/resources/lib</directory>-->
<!--                <targetPath>BOOT-INF/lib/</targetPath>-->
<!--                <includes>-->
<!--                    <include>**/*.jar</include>-->
<!--                </includes>-->
<!--            </resource>-->
<!--            <resource>-->
<!--                <directory>src/main/resources</directory>-->
<!--                <targetPath>BOOT-INF/classes/</targetPath>-->
<!--            </resource>-->
<!--            <resource>-->
<!--                <directory>src/main/resources</directory>-->
<!--                <includes>-->
<!--                    &lt;!&ndash;   <include>**/*.properties</include>&ndash;&gt;-->
<!--                    &lt;!&ndash;  <include>**/*.xml</include>&ndash;&gt;-->
<!--                    <include>**/*.*</include>-->
<!--                </includes>-->
<!--                <filtering>true</filtering>-->
<!--            </resource>-->
<!--        </resources>-->

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.bw.saml.App</mainClass>
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>pfx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>cer</nonFilteredFileExtension>
                        <nonFilteredFileExtension>jks</nonFilteredFileExtension>
                        <nonFilteredFileExtension>publicKeys.store</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>aliyun</id>
            <name>aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>aliyun</id>
            <name>aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>
